language: "python"
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"
   - "pypy"
install:
   - pip install flake8
   - pip install codecov
before_script:
   flake8 .
script:
   - coverage run --branch --source=geojson setup.py test
   - coverage xml
after_success:
   - codecov
