language: "python"
python:
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   - "pypy"
   - "pypy3"
install:
   pip install flake8
   pip install coveralls
before_script:
   flake8 .
script: 
   coverage run --source=geojson setup.py test
after_success:
   coveralls
